=== gazampa/codebunker/java/random/dom/slideshow3.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!--
    DTD for a simple "slide show".
-->

<!ELEMENT slideshow (slide+)>
<!ATTLIST slideshow 
            title    CDATA    #REQUIRED
            date     CDATA    #IMPLIED
            author   CDATA    "unknown"
>
<!ELEMENT slide (image?, slide-title?, item*)>
<!ATTLIST slide 
            type   (tech | exec | all) #IMPLIED
>

<!-- Defines the %inline; declaration -->
<!ENTITY % xhtml SYSTEM "xhtml.dtd">
%xhtml;

<!ELEMENT slide-title (%inline;)*>
<!ELEMENT item (%inline; | item)* >
<!ELEMENT image EMPTY>
<!ATTLIST image 
            alt    CDATA    #IMPLIED
            src    CDATA    #REQUIRED
            type   CDATA    "image/gif"
>

=== gazampa/codebunker/java/random/dom/slideSample10.xml
<?xml version='1.0' encoding='utf-8'?>

<!--  A SAMPLE set of slides  -->

<!DOCTYPE slideshow SYSTEM "slideshow3.dtd" [
  <!ENTITY product  "WonderWidget">
  <!ENTITY products "WonderWidgets">   <!-- FOR WALLY / WALLIES -->
  <!ENTITY copyright SYSTEM "copyright.xml">
]>

<!-- SUBSTITUTIONS WORK IN ATTRIBUTES, TOO -->
<slideshow 
    title="&product; Slide Show"
    date="Date of publication"
    author="Yours Truly"
    >

    <!-- PROCESSING INSTRUCTION -->
    <?my.presentation.Program QUERY="exec, tech, all"?>

    <!-- TITLE SLIDE -->
    <slide type="all">
       <slide-title>Wake up to &products;!</slide-title>
    </slide>

    <!-- TITLE SLIDE -->
    <slide type="all">
       <item>&copyright;</item>
    </slide>

    <!-- OVERVIEW -->
    <slide type="all">
      <slide-title>Overview</slide-title>
      <item>Why <em>&products;</em> are great</item>
      <item/>
      <item>Who <em>buys</em> &products;</item>
    </slide>

    <slide type="tech">
      <slide-title>How it Works</slide-title>
      <item>First we fozzle the frobmorten</item>
      <item>Then we framboze the staten</item>
      <item>Finally, we frenzle the fuznaten</item>
      <item><![CDATA[Diagram:
                         
    frobmorten <------------ fuznaten
        |            <3>        ^
        | <1>                   |   <1> = fozzle
        V                       |   <2> = framboze    
      staten--------------------+   <3> = frenzle
                     <2>
      ]]></item>
    </slide>

</slideshow>
